server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: change_here
    username: change_here
    password: change_here
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

personal-project:
  url:
    auth: change_here
    admin: change_here
  hashing:
    algorithm: SHA-256
    salt: change_here
  jwt:
    secret: change_here
    lifespan-millisecond:
      access-token: 600000 # 1000 * 60 * 10 = 10 minutes
      refresh-token: 10800000 # 1000 * 60 * 60 * 3 = 3 hours
  redis:
    host: change_here
    port: change_here
  cookie:
    access-token: "accessToken"
    refresh-token: "refreshToken"
