server:
  port: 8081
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: db_server_url_here
    username: db_username
    password: db_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

personal-project:
  url:
    auth: auth_server_url
    admin: admin_server_url
    db: db_server_url
    cache: cache_server_url
  hashing:
    alg: SHA-256
    salt: your_salt_here
