server:
  port: 8081
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_project
    username: jihyokim
    password: Sdb1214##
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

personal-project:
  url:
    auth: http://localhost:8080/
    admin: http://localhost:8081/
  hashing:
    algorithm: SHA-256
    salt: MjAyMSBTR1MgRGV2IENhbXAgMm5kIFRlYW0gTGFzdCBQdW5jaCBKaWh5byBLaW0=
  jwt:
    secret: bWlLIG95aGlKIGhjbnVQIHRzYUwgbWFlVCBkbjIgcG1hQyB2ZUQgU0dTIDEyMDI=
    lifespan-millisecond:
      access-token: 600000 # 1000 * 60 * 10 = 10 minutes
      refresh-token: 10800000 # 1000 * 60 * 60 * 3 = 3 hours
  redis:
    host: localhost
    port: 6379
  cookie:
    access-token: "accessToken"
    refresh-token: "refreshToken"
